# Computer Vision 

# Exercise 1: Introduction To Python, NumPy And Matplotlib

- TU Chemnitz
    - Fak. für Informatik
        - Professur Künstliche Intelligenz
            - Lehre
                - Bildverstehen
     
Contact:
* julien dot vitay at informatik dot tu-chemnitz dot de
* abbas dot al-ali at informatik dot tu-chemnitz dot de

Course web page:
[https://www.tu-chemnitz.de/informatik/KI/edu/biver/](https://www.tu-chemnitz.de/informatik/KI/edu/biver/)

## Exercise 1-2: Introduction To NumPy And Matplotlib

## 1. NumPy Numerical Library
- NumPy is a linear algebra library written in Python.
- The reference manual is at [http://docs.scipy.org/doc](http://docs.scipy.org/doc)
- A nice tutorial can be found at [https://docs.scipy.org/doc/numpy/user/quickstart.html](https://docs.scipy.org/doc/numpy/user/quickstart.html)
- A detailed list of all available functions (with examples) is at [https://docs.scipy.org/doc/numpy/reference/routines.html](https://docs.scipy.org/doc/numpy/reference/routines.html)
- If you already know Matlab, a comparison is at [https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html](https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html)

Importing the library

- You can write at the beginning of your script:
```python
from numpy import *
```
- All the a vailables functions are then imported into your working space.
- It is often better to keep a short namespace, as it could overload other library definitions:
```python
import numpy as np 
```
- You can get help on any NumPy function:
```python
help(np.array)
help(np.ndarray.transpose)
```

### 1.A. Vectors And Matrices

-   The basic object in NumPy is an array with d-dimensions (1 = vector,2 = matrix, etc...). They can store either integers or floats.

-   In order to create a vector of three floats, you simply have to call the `array()` method giving the list of the floats as input:

```python
list_of_floats =  [ 1., 2., 3.]
V = np.array( list_of_floats )
```

- Each initial element of the vector has to be given inside a Python list. For a 3*4 matrix of 8 bits unsigned integers, it is:

```python
list_of_lists = [ [ 1, 2, 3, 4],[ 5, 6, 7, 8],[ 4, 3, 2, 1] ]
M = np.array( list_of_lists , dtype=np.uint8)
```

- Most of the time you don't care about the type in Python (the default floating-point precision is what you want), but if you need it, you can always specify it with the parameter dtype={int32, uint16, float64, ...}.

- Matrices should be initialized with a list of lists. The elements of the array are internally stored in a sequence, so you can easily reshape vectors or matrices using the `reshape()` method. The `shape` propertey gives the shape of an array, `dtype` its associated data type.


### 1.B. Attributes Of An Array

The following attributes of an array can be accessed:

- `A.shape` : returns the shape of the vector or matrix (row, column)

- `A.size` : returns the total number of elements in the array

- `A.ndim` : returns the number of dimensions of the array (vector: 1, matrix:2)

- `A.dtype.name` : returns the type of data stored in the array (int32, uint16, float64...)

- `A.itemsize` : returns the size in bytes of each element.

Run the following cells and watch the results. Change the values, type or the number of the elements and run again.

In [4]:
from __future__ import print_function
import numpy as np

list_of_floats =  [ 1., 2., 3.]
V = np.array( list_of_floats )

print('Type of elements in V is :',V.dtype)
print('Type of V.shape is :',type(V.shape))
print('Shape of V is :',V.shape)
print('V is:')
print(V)

Type of elements in V is : float64
Type of V.shape is : <class 'tuple'>
Shape of V is : (3,)
V is:
[1. 2. 3.]


In [3]:
list_of_lists = [ [ 1, 2, 3, 4],[ 5, 6, 7, 8],[ 4, 3, 2, 1] ]
M = np.array( list_of_lists , dtype=np.uint8)
# do the same with M

print('Type of elements in M is :', M.dtype)
print('Type of M.shape is :',type(M.shape))
print('Shape of M is :',M.shape)
print('M is:')
print(M)

Type of elements in M is : uint8
Type of M.shape is : <class 'tuple'>
Shape of M is : (3, 4)
M is:
[[1 2 3 4]
 [5 6 7 8]
 [4 3 2 1]]


In [4]:
A = np.array([ 1, 2, 3, 4, 5, 6, 7, 8])
print('Shape of A is :',A.shape)
print('A is:')
print(A)

print('\nA.reshape(2,4):\n',A.reshape(2,4))
print('\nA:\n',A)

B = A.reshape(2,4)
print('\nB:\n',B)
print('\nA:\n',A)

B.shape = (8,1)
print('\nB:\n',B)
print('\nA:\n',A)

Shape of A is : (8,)
A is:
[1 2 3 4 5 6 7 8]

A.reshape(2,4):
 [[1 2 3 4]
 [5 6 7 8]]

A:
 [1 2 3 4 5 6 7 8]

B:
 [[1 2 3 4]
 [5 6 7 8]]

A:
 [1 2 3 4 5 6 7 8]

B:
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]

A:
 [1 2 3 4 5 6 7 8]


### 1.C. Initialization Of An Array

Here are some specific initializations for vectors/matrices:

In [12]:
# A 2*3 matrix filled with 0.0
A = np.zeros((2,3))  

# A vector of 12 elements initialized to 1.0
B = np.ones(12,dtype=int)  

# A vector of 11 elements whose value linearly
# increases from 0.0 to 1.0
C = np.linspace(0.0, 1.0, 11) 

# A 2*5 matrix with values randomly taken 
# from an uniform distribution between 0.0 and 1.0.
D = np.random.uniform(0.0, 1.0, (2, 5)) 

# A 3*5 matrix with values randomly taken from
# a normal (gaussian) distribution 
# with a mean of 0.5 and standard deviation of 1.0.
E = np.random.normal(0.5, 1.0, (3, 5)) 

# A 2*4*3 array (two 4*3 pages)
F = np.arange(24).reshape((2,4,3))

print('\n',A)
print('\n',B)
print('\n',C)
print('\n',D)
print('\n',E)
print('\n',F[0,:,:])


 [[0. 0. 0.]
 [0. 0. 0.]]

 [1 1 1 1 1 1 1 1 1 1 1 1]

 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]

 [[0.97351848 0.32495284 0.52687318 0.70344886 0.78708592]
 [0.56782209 0.46771084 0.92099362 0.12888155 0.35928558]]

 [[ 1.1076766  -1.15934343  0.60993652  1.43865386  0.88390597]
 [ 0.64322096  0.44070071 -1.86630104  0.47502082  1.5611926 ]
 [ 1.29941939  0.86010142  1.92324201 -0.18004065  0.60782858]]

 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


### 1.D. Manipulation Of Matrices: Indices, Slices

- To access a particular element of a matrix, you can use the usual Python list style (the first element has a rank of 0):

In [13]:
#A = np.arange(1,13).reshape((3,4))
A = np.array([ 
        [ 1, 2 , 3 , 4 ],
        [ 5, 6 , 7 , 8 ],
        [ 9, 10, 11, 12]])

print('\n',A)

B = A[0, 2] 
C = A[:, 1] 
D = A[:, 1:3] 
E = A[-1,:] 

print('\n',B)
print('\n',C)
print('\n',D)
print('\n',E)

# on the left side
A[0,0] = -1
A[2,-1:0:-1] = A[:,0]
A[:,-1] = [100,200,300]
print('\n',A)


 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 3

 [ 2  6 10]

 [[ 2  3]
 [ 6  7]
 [10 11]]

 [ 9 10 11 12]

 [[ -1   2   3 100]
 [  5   6   7 200]
 [  9   9   5 300]]


- To perform conditional manipulation of matrix content, one can retrieve the indices easily:

In [14]:
A = np.array( 
    [ [ -2,  2,  1, -4],
      [  3, -1, -5, -3] ])
negatives = A < 0
A[negatives] = 0

print(negatives)
print(A)

# or simply
#A[A < 0] = 0
#print(A)

[[ True False False  True]
 [False  True  True  True]]
[[0 2 1 0]
 [3 0 0 0]]


### 1.E. Basic Linear Algebra 

- Let's define some matrices:

In [15]:
A = np.array( [ [ 1, 2, 3, 4],
                [ 5, 6, 7, 8] ])

B = np.array( [ [ 1, 2],
                [ 3, 4],
                [ 5, 6],
                [ 7, 8] ])

C = np.array( [ [  1,  2,  3,  4],
                [  5,  6,  7,  8],
                [  9, 10, 11, 12],
                [ 13, 14, 15, 16] ])

#### 1.E.a. Transpose A Matrix 

- A matrix can be transposed with the `transpose()` method or the `.T` shortcut:

In [16]:
D = A.transpose() 
E = A.T # equivalent but simpler

print(A)
print('\n',D)
print('\n',E)

[[1 2 3 4]
 [5 6 7 8]]

 [[1 5]
 [2 6]
 [3 7]
 [4 8]]

 [[1 5]
 [2 6]
 [3 7]
 [4 8]]


- `transpose()` does not change `A`, only the returns a transposed copy. To change `A` use am assigment `A = A.T`

#### 1.E.b. Multiply Two Matrices 

- element-wise: Two arrays of **exactly** the same size can be multiplied *element-wise* by using the `*` operator.

- algebrically: To perform a **matrix multiplication**, you have to use the `dot()` method.
    + One dimension must match! `(m, n) * (n, p) = (m, p)`

In [17]:
A = np.array( [ [ 1, 2, 3, 4],
                [ 5, 6, 7, 8] ])
B = np.array( [ [ 1, 2],
                [ 3, 4],
                [ 5, 6],
                [ 7, 8] ])
C = A * B.T
D = A.T * B

print(C)
print('\n',D)

E = np.dot(A, B)
F = np.dot(B, A)

print('\n',E)
print('\n',F)


[[ 1  6 15 28]
 [10 24 42 64]]

 [[ 1 10]
 [ 6 24]
 [15 42]
 [28 64]]

 [[ 50  60]
 [114 140]]

 [[11 14 17 20]
 [23 30 37 44]
 [35 46 57 68]
 [47 62 77 92]]


#### 1.E.c. Inversing A Matrix

- Inversing a Matrix (when possible) can be done using the `inv()` method whitch is defined in the `linalg` submodule of NumPy.

In [18]:
A = np.array( [ [  1,  2,  3,  4],
                [  5,  6,  7,  8],
                [  9, 10, 11, 12],
                [ 13, 14, 15, 16] ])

A_INV = np.linalg.inv(A)
print(A_INV)
print(np.dot(A,A_INV))

print(np.linalg.det(A))

A = np.array( [ [  1,  2],
                [  5,  6]])

A_INV = np.linalg.inv(A)
print(A_INV)
print(np.dot(A,A_INV))

print(np.linalg.det(A))

[[ 1.50119988e+15 -3.75299969e+14 -3.75299969e+15  2.62709978e+15]
 [-1.95155984e+16  1.95155984e+16  1.95155984e+16 -1.95155984e+16]
 [ 3.45275971e+16 -3.79052969e+16 -2.77721977e+16  3.11498974e+16]
 [-1.65131986e+16  1.87649984e+16  1.20095990e+16 -1.42613988e+16]]
[[  0. -16.   0.   0.]
 [  0.   0. -32.   0.]
 [-64.   0.   0.   0.]
 [  0.   0. -64.  64.]]
-1.820448242817726e-31
[[-1.5   0.5 ]
 [ 1.25 -0.25]]
[[1. 0.]
 [0. 1.]]
-3.999999999999999


### 1.F. Summing Elements 

- One can sum the elements of a matrix globally, row-wise or column-wise:

In [19]:
A = np.array( [ [ 1, 2, 3, 4],
                [ 5, 6, 7, 8] ])

# Globally
S1 = np.sum(A)

# Per column
S2 = np.sum(A, axis=0) 

# Per row
S3 = np.sum(A, axis=1) 

print(S1);print(S2);print(S3)


36
[ 6  8 10 12]
[10 26]


### 1.G. Mathematical Operations 

- You can apply any usual mathematical operations (cos, sin, exp, etc...) on each element of a matrix:

In [20]:
A = np.array( [ [ 1, 2, 3, 4],
                [ 5, 6, 7, 8] ])
B = np.exp(A)
C = np.cos(A)
D = np.log(A)
E = (A+3) * np.cos(A-2)

print(B);print('\n',C);print('\n',D);print('\n',E)

[[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01]
 [1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03]]

 [[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
 [ 0.28366219  0.96017029  0.75390225 -0.14550003]]

 [[0.         0.69314718 1.09861229 1.38629436]
 [1.60943791 1.79175947 1.94591015 2.07944154]]

 [[ 2.16120922  5.          3.24181384 -2.91302786]
 [-7.91993997 -5.88279259  2.83662185 10.56187315]]


## 2. Matplotlib

- Matplotlib is a python 2D plotting library which produces publication quality figures in a variety of hardcopy formats and interactive environments across platforms.

![](img/matplotlib.png)

- Reference: <http://matplotlib.org>

- Tutorial by N. Rougier: <http://www.labri.fr/perso/nrougier/teaching/matplotlib>

- Simply imported with :

```python
import matplotlib.pyplot as plt
```

- In the B202, one has to explicitly specify the backend:

In [2]:
import matplotlib
matplotlib.use('TKAgg')
import matplotlib.pyplot as plt

### 2.A. Plotting The Graph Of A Function

- The `plot` command allows to make simple line drawings:

In [10]:
# prepare the data
X = np.linspace(0., 10., 100)
Y = X**2 + 1.

# then plot them
plt.figure(figsize=(10, 10))
plt.plot(X, Y, '.')
plt.show()
print(X)
print(Y)

[ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777778
  7.87878788  7.97979798  8.08080808  8.18181818  8

- `plot()` takes two vectors X and Y and a style (here a line '-', but colored dots are possible).

- The call to `show()` is obligatory at the end to display the window!

### 2.B. Nicer Axes

In [6]:
import numpy as np
import matplotlib.pyplot as plt

X = np.linspace(0., 10., 100)
Y = X**2 + 1.

plt.plot(X, Y, '-')
plt.title('A quadratic function of x')
plt.xlabel('x')
plt.ylabel('$y = x^2 + 1$')
plt.show()

### 2.C. Two Plots With A Legend

In [11]:
import numpy as np
import matplotlib.pyplot as plt

X = np.linspace(0., 10., 100)
Y = X**2 + 1.
Z = 100./(X**2 + 1.)

plt.plot(X, Y, '-', label='y')
plt.plot(X, Z, '-', label='z')
plt.title('Two functions of x')
plt.xlabel('x')
plt.ylabel('y and z')
plt.legend()
plt.show()

### 2.D. Two Plots Side By Side

In [8]:
import numpy as np
import matplotlib.pyplot as plt

X = np.linspace(0., 10., 100)
Y = X**2 + 1.
Z = 100./(X**2 + 1.)

plt.subplot(121)
plt.plot(X, Y, '-', label='y')
plt.xlabel('x')
plt.ylabel('y')
plt.subplot(122)
plt.plot(X, Z, '-', label='z')
plt.xlabel('x')
plt.ylabel('z')
plt.show()

### 2.E. Plotting Matrices / Images

- Matrices can be displayed using `imshow()`

- You can choose the color code with the `cmap` argument.

- The interpolation method can also be selected for small matrices (`interpolation="bicubic"`).

- (0, 0) is at the top-left of the image, the first axis is vertical. Change it with the `origin` parameter.

In [11]:
import numpy as np
import matplotlib.pyplot as plt

img = np.random.uniform(0., 1., (600, 800))

plt.imshow(img, cmap=plt.cm.gray)
plt.show()

## 3. Exercises

### 3.A. Basic Linear Algebra

-   Write the following system of equations in the matrix form ($A \cdot X = B$) and solve it using NumPy. Check that it worked.

$$
\begin{cases}
\begin{array}{lll}
2\cdot x_1 + x_2+ x_3 & = & 9 \\
x_1 + 2\cdot x_2 + x_4 & = & 8 \\
x_1 + 2\cdot x_2 + 3\cdot x_3 +2 \cdot x_4 & = & 7 \\
2\cdot x_2 + x_3 +2 \cdot x_4 & = & 6 \\
\end{array}
\end{cases}
$$


-   What are the eigenvalues and eigenvectors of the matrix A defined
    above? (tip: read the doc for the function `np.linalg.eigh`)

### 3.B Rotation Of A Vector

-   Write a function that rotates a 2D vector by an angle $\theta$.

$$\begin{bmatrix} 
    x' \\ 
    y' 
\end{bmatrix} = \begin{bmatrix} 
                    \cos \theta & -\sin \theta \\ 
                    \sin \theta & \cos \theta 
                \end{bmatrix} 
                \cdot 
                \begin{bmatrix} 
                    x \\ 
                    y 
                \end{bmatrix}$$

# 3.A. Basic Linear Algebra Solution

In [61]:
#Write the following system of equations in the matrix form ( 𝐴⋅𝑋=𝐵 ) and solve it using NumPy. 
#Check that it worked.
import numpy as np

A = np.array( [ [2,1,1,0],
                [1,2,0,1],
                [1,2,3,2],
                [0,2,1,2] ] )

B = np.array( [9,8,7,6] )

X = np.dot(np.linalg.inv(A), B)

for idx, value in enumerate(X, start=1):
    print("x" + str(idx) + " = " + str(value))

print()
print(X)
print()

print("A*X = " + str(np.dot(A,X)) + " = B = " + str(B))

x1 = 13.000000000000014
x2 = -11.000000000000021
x3 = -6.000000000000007
x4 = 17.00000000000002

[ 13. -11.  -6.  17.]

A*X = [9. 8. 7. 6.] = B = [9 8 7 6]


In [63]:
#What are the eigenvalues and eigenvectors of the matrix A defined above? 
import numpy as np

A = np.array( [ [2,1,1,0],
                [1,2,0,1],
                [1,2,3,2],
                [0,2,1,2] ] )

eigenvalues, eigenvectors = np.linalg.eig(A)

print("The eigenvalues of matrix A are:")
for idx, eigenvalue in enumerate(eigenvalues, start=1):
    print("lambda" + str(idx) + " = " + str(eigenvalue))

print()

print("The eigenvectors of matrix A are (columnwise):")
print(eigenvectors)
print()

for idx, eigenvector in enumerate(eigenvectors.T, start=1):
    print("v" + str(idx) + " = " + str(eigenvector))

print()
    
# let's check if the eigenvalues and eigenvectors satisfy the condition of: A*v = lambda*v ==> A*v - lambda*v = 0
print("Sanity check, the following vectors should all be zero vectors:")
for eigenvalue, eigenvector in zip(eigenvalues, eigenvectors.T):
    print(np.dot(A, eigenvector) - eigenvalue * eigenvector)

The eigenvalues of matrix A are:
lambda1 = (5.084437874945341+0j)
lambda2 = (0.0504760478613856+0j)
lambda3 = (1.9325430385966396+0.4021825006405717j)
lambda4 = (1.9325430385966396-0.4021825006405717j)

The eigenvectors of matrix A are (columnwise):
[[ 0.34062178+0.j          0.40203011+0.j         -0.07534056-0.54847208j
  -0.07534056+0.54847208j]
 [ 0.24680683+0.j         -0.55970515+0.j         -0.38971025+0.00669761j
  -0.38971025-0.00669761j]
 [ 0.80381987+0.j         -0.22406218+0.j          0.61537837+0.j
   0.61537837-0.j        ]
 [ 0.42063857+0.j          0.68912848+0.j          0.09893557+0.39128564j
   0.09893557-0.39128564j]]

v1 = [0.34062178+0.j 0.24680683+0.j 0.80381987+0.j 0.42063857+0.j]
v2 = [ 0.40203011+0.j -0.55970515+0.j -0.22406218+0.j  0.68912848+0.j]
v3 = [-0.07534056-0.54847208j -0.38971025+0.00669761j  0.61537837+0.j
  0.09893557+0.39128564j]
v4 = [-0.07534056+0.54847208j -0.38971025-0.00669761j  0.61537837-0.j
  0.09893557-0.39128564j]

Sanity check, the fol

Write a function that rotates a 2D vector by an angle  𝜃.

# 3.B Rotation Of A Vector Solution

In [65]:
import numpy as np

def rotateVector2D(someVector, theta):
    result = None
    if someVector.shape == (2,):
        rotationMatrix = np.array( [ [np.cos(theta), -np.sin(theta)],
                                     [np.sin(theta), np.cos(theta)] ] )
        result = np.dot(rotationMatrix, someVector)
    return result

V = np.array( [1,0] )
theta = 3 * np.pi / 2
print(theta)

print("A rotation of vector V = " + str(V) + " by theta = " +
      str(np.rad2deg(theta)) + "° results in V' = " + str(rotateVector2D(V, theta)) + ".")

4.71238898038469
A rotation of vector V = [1 0] by theta = 270.0° results in V' = [-1.8369702e-16 -1.0000000e+00].
